# Generated by Django 5.2.6 on 2025-09-27 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='trans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('amount', models.FloatField()),
            ],
        ),
    ]
