# Generated by Django 5.2.6 on 2025-09-27 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trans',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
