# Generated by Django 5.2.6 on 2025-09-28 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0002_trans_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trans',
            old_name='Description',
            new_name='description',
        ),
    ]
