# Generated by Django 5.2.6 on 2025-09-30 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('target', '0006_alter_budget_target_month_id'),
        ('trans', '0003_rename_description_trans_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='trans',
            name='category_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='target.categories_table'),
        ),
    ]
