# Generated by Django 5.2.6 on 2025-10-01 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('target', '0007_remove_categories_table_distribution'),
        ('trans', '0004_trans_category_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='categorization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('keyword', models.CharField(max_length=100)),
                ('category_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='target.categories_table')),
            ],
        ),
    ]
