# Generated by Django 5.2.6 on 2025-10-03 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0005_categorization'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorization',
            name='IO',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='categorization',
            name='keyword',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='trans',
            name='description',
            field=models.CharField(max_length=255),
        ),
    ]
