# Generated by Django 5.2.6 on 2025-10-03 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0006_categorization_io_alter_categorization_keyword_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorization',
            name='IO',
        ),
        migrations.AddField(
            model_name='trans',
            name='IO',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
