# Generated by Django 5.2.6 on 2025-10-03 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0007_remove_categorization_io_trans_io'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Bank', models.CharField(max_length=255)),
            ],
        ),
    ]
