# Generated by Django 5.2.6 on 2025-10-03 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0008_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='trans',
            name='Bank_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trans.bank'),
        ),
    ]
