# Generated by Django 5.2.6 on 2025-10-03 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0009_trans_bank_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
