# Generated by Django 5.2.6 on 2025-10-03 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0010_bank_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='Bank',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
