# Generated by Django 5.2.6 on 2025-10-03 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0011_alter_bank_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='Bank',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
