# Generated by Django 5.2.6 on 2025-10-04 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_accounts_bank'),
        ('trans', '0012_alter_bank_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trans',
            name='Bank_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.bank'),
        ),
        migrations.DeleteModel(
            name='Bank',
        ),
    ]
