# Generated by Django 5.2.6 on 2025-10-05 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_accounts_account_name_alter_accounts_account_type'),
        ('trans', '0013_alter_trans_bank_id_delete_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trans',
            name='Bank_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.accounts'),
        ),
    ]
