# Generated by Django 5.2.6 on 2025-10-05 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0014_alter_trans_bank_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trans',
            old_name='Bank_id',
            new_name='Accounts_id',
        ),
    ]
