# Generated by Django 5.2.6 on 2025-10-05 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_accounts_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='account_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='account_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
